apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: letsencrypt-client-{{ SCHOOL_ID }}-prod@digitcore.cm
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - http01:
          ingress:
            class: traefik

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-fake
spec:
  acme:
    email: letsencrypt-client-{{ SCHOOL_ID }}-fake@digitcore.cm
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-fake-account-key
    solvers:
      - http01:
          ingress:
            class: traefik
