apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: client
          image: "ghcr.io/emenec-finance/school-clients/school-client-{{SCHOOL_ID}}-staging:{{TAG}}"
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
            requests:
              cpu: "150m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: api/healthz/live
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: api/healthz/live
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
