apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sslredirect
  namespace: kube-system
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sslredirect-http
  namespace: kube-system
spec:
  redirectScheme:
    scheme: http
    permanent: true
