apiVersion: v1
kind: PersistentVolume
metadata:
  name: emfi-school-postgres-staging
spec:
  storageClassName: standard
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadOnlyMany
  capacity:
      storage: 2Gi
  local:
    path: /mnt/emfi/school/postgres/data/staging
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - emfi # Cluster/node name

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: school-staging
spec:
  volumeName: emfi-school-postgres-staging
  storageClassName: standard
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
