apiVersion: v1
kind: PersistentVolume
metadata:
  name: emfi-school-redis-staging
spec:
  storageClassName: standard
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
      storage: 1Gi
  local:
    path: /mnt/emfi/school/redis/data/staging
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - emfi # Cluster/node name

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: school-staging
spec:
  volumeName: emfi-school-redis-staging
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
