apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-dev
  namespace: school-dev
spec:
  storageClassName: standard
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  capacity:
      storage: 1Gi
  local:
    path: /mnt/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - vmi2139037.contaboserver.net # Cluster/node name

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-dev
  namespace: school-dev
spec:
  volumeName: postgres-dev
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
