apiVersion: v1
kind: PersistentVolume
metadata:
  name: emfi-school-postgres-dev
spec:
  storageClassName: standard
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
      storage: 2Gi
  local:
    path: /mnt/node/data/apps/emfi/school/postgres/dev
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - emfi # Cluster/node name

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: school-dev
spec:
  volumeName: emfi-school-postgres-dev
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
