apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-school
  namespace: school-dev
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-sslredirect@kubernetescrd
    cert-manager.io/cluster-issuer: "letsencrypt-fake"
spec:
  ingressClassName: traefik
  rules:
    - host: dev.api.digitcore.cm
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 3100
    - host: dev.digitcore.cm
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin
                port:
                  number: 3000
  tls:
    - hosts:
        - dev.api.digitcore.cm
        - dev.digitcore.cm
      secretName: school-tls-secret
