# Web socket API
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-school-api-websocket
  namespace: school-dev
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.priority: "100"
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-websocket-headers@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: dev.api.digitcore.cm
      http:
        paths:
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 3100
---
# Http API
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-school-api-http
  namespace: school-dev
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.priority: "10"
spec:
  ingressClassName: traefik
  rules:
    - host: dev.api.digitcore.cm
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 3100
---
# Http Admin
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-school-admin-http
  namespace: school-dev
  annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: dev.digitcore.cm
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin
                port:
                  number: 3000
---
# Http CDN
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-school-cdn-http
  namespace: school-dev
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: dev.cdn.digitcore.cm
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cdn
                port:
                  number: 3100
