apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-school
  namespace: school-staging
  annotations:
    ingressClassName: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: sslredirect@kubernetescrd
    cert-manager.io/cluster-issuer: "letsencrypt-fake"
spec:
  rules:
    - host: staging.api.digitcore.cm
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 3100
    - host: staging.digitcore.cm
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin
                port:
                  number: 3000
  tls:
    - hosts:
        - staging.api.digitcore.cm
      secretName: api-tls-secret
    - hosts:
        - staging.digitcore.cm
      secretName: admin-tls-secret
