apiVersion: v1
kind: PersistentVolume
metadata:
  name: emfi-school-postgres-prod
spec:
  storageClassName: standard
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
      storage: 200Gi
  local:
    path: /mnt/emfi/school/postgres/data/prod
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - emfi # Cluster/node name

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: school-prod
spec:
  volumeName: emfi-school-postgres-prod
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---
volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi