apiVersion: v1
kind: PersistentVolume
metadata:
  name: emfi-school-redis-prod
  namespace: school-prod
spec:
  storageClassName: standard
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  capacity:
      storage: 10Gi
  local:
    path: /mnt/emfi/school/redis/data/prod
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - emfi # Cluster/node name

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: school-prod
spec:
  volumeName: emfi-school-redis-prod
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
