apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-prod
  namespace: school-prod
spec:
  storageClassName: standard
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  capacity:
      storage: 5Gi
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - vmi2139037.contaboserver.net # Cluster/node name

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-prod
  namespace: school-prod
spec:
  volumeName: redis-prod
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
