apiVersion: v1
kind: PersistentVolume
metadata:
  name: school-redis-prod
spec:
  storageClassName: standard
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
      storage: 10Gi
  local:
    path: /mnt/node/data/apps/school/redis/prod
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - digitcore # Cluster/node name

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: school-prod
spec:
  volumeName: school-redis-prod
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
