apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: client
          image: "ghcr.io/Allatchimi/school-clients-deployment/school-client-{{SCHOOL_ID}}-dev:{{TAG}}"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
            requests:
              cpu: "150m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: api/healthz/live
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: api/healthz/live
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
