apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: school-prod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: admin
  admin:
    metadata:
      labels:
        app: admin
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: admin
          image: "ghcr.io/emenec-finance/school-template/school-admin-staging:45"
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "250m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: api/healthz/live
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: api/healthz/live
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
