apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: school-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: admin
          image: "ghcr.io/emenec-finance/school-admin/school-admin:4"
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: admin-env-secret
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "250m"
              memory: "512Mi"
