apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn
  namespace: school-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdn
  template:
    metadata:
      labels:
        app: cdn
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: cdn
          image: "ghcr.io/allatchimi/cdn/cdn:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 3100
          envFrom:
            - secretRef:
                name: cdn-env-secret
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            tcpSocket:
              port: 3100
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 3100
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
