apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: school-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
      - name: postgres-volume
        persistentVolumeClaim:
          claimName: postgres
      containers:
      - name: postgres
        image: "postgres:16-alpine"
        ports:
        - containerPort: 5432
        envFrom:
          - configMapRef:
              name: postgres-env-config
        volumeMounts:
        - name: postgres-volume
          mountPath: /var/lib/postgresql/data
        resources:
          limits:
            cpu: "6"
            memory: "16Gi"
          requests:
            cpu: "3"
            memory: "8Gi"
