apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: school-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
      - name: redis-volume
        persistentVolumeClaim:
          claimName: redis
      containers:
      - name: redis
        image: "redis:7-alpine"
        ports:
        - containerPort: 6379
        envFrom:
          - configMapRef:
              name: redis-env-config
        volumeMounts:
        - name: redis-volume
          mountPath: /data
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
