apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: sslredirect
  namespace: default
spec:
  redirectRegex:
    regex: "^http://(.*)"
    replacement: "https://$1"
    permanent: true