apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: school-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: api-env-volume
          configMap:
            name: api-env-config
        - name: api-jwt-volume
          configMap:
            name: api-jwt-config
      containers:
        - name: api
          image: "ghcr.io/emenec-finance/school-api/school-api:8"
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: api-env-volume
              mountPath: /app
            - name: api-jwt-volume
              mountPath: /app/assets/private/keys/jwt
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            exec:
              command:
                - ls
                - /app
            initialDelaySeconds: 5
            periodSeconds: 5
