apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: school-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: api
        image: "ghcr.io/emenec-finance/school/api:3"
        ports:
        - containerPort: 3100
        envFrom:
          - secretRef:
              name: app-secret
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          exec:
            command:
            - ls
            - /app
          initialDelaySeconds: 5
          periodSeconds: 5
