apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: school-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: api-env-volume
          configMap:
            name: api-env-config
            items:
              - key: app.env
                path: app.env
        - name: api-jwt-volume
          configMap:
            name: api-jwt-config
            items:
              - key: private.pem
                path: private.pem
              - key: public.pem
                path: public.pem
      containers:
        - name: api
          image: "ghcr.io/emenec-finance/school-api/school-api:14"
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: api-env-volume
              mountPath: /app/app.env
              subPath: app.env
            - name: api-jwt-volume
              mountPath: /app/assets/private/keys/jwt/private.pem
              subPath: private.pem
            - name: api-jwt-volume
              mountPath: /app/assets/private/keys/jwt/public.pem
              subPath: public.pem
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
