apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: school-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-data-volume
          persistentVolumeClaim:
            claimName: postgres
      containers:
        - name: postgres
          image: "postgres:16"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-env-config
          volumeMounts:
            - name: postgres-data-volume
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 30
            periodSeconds: 10
