apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: school-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
        - name: redis-volume
          persistentVolumeClaim:
            claimName: redis
      containers:
        - name: redis
          image: "redis:7"
          ports:
            - containerPort: 6379
          envFrom:
            - configMapRef:
                name: redis-env-config
          volumeMounts:
            - name: redis-volume
              mountPath: /data
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
