name: School Production CI
run-name: ${{ github.actor }} is deploying School to Production
on:
  push:
    branches: [main] # Branch name
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
jobs:
  deploy-school-k3s:
    runs-on: ubuntu-latest
    env:
      POSTGRES_ENV: ${{ secrets.PROD_POSTGRES_ENV }}
      REDIS_ENV: ${{ secrets.PROD_REDIS_ENV }}
      API_ENV: ${{ secrets.PROD_API_ENV }}
      API_JWT_PRIVATE_KEY: ${{ secrets.PROD_API_JWT_PRIVATE_KEY }}
      API_JWT_PUBLIC_KEY: ${{ secrets.PROD_API_JWT_PUBLIC_KEY }}

      API_TLS_CERT: ${{ secrets.PROD_API_TLS_CERT }}
      API_TLS_KEY: ${{ secrets.PROD_API_TLS_KEY }}
      ADMIN_TLS_CERT: ${{ secrets.PROD_ADMIN_TLS_CERT }}
      ADMIN_TLS_KEY: ${{ secrets.PROD_ADMIN_TLS_KEY }}

      NAMESPACE: "school-prod"
    environment:
      name: "Production"
      url: https://school.emfi.cm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          ref: "main" # Branch name

      - name: Install SSH keys
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Remove old project files from server
        continue-on-error: true
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            mkdir -p ${{ secrets.PROD_WORK_DIR }}
            cd ${{ secrets.PROD_WORK_DIR }}
            rm -rf school-deployment
          EOF

      - name: Copy the repository files to the server
        run: |
          scp -P 22 -i ~/.ssh/id_rsa -r ../school-deployment ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.PROD_WORK_DIR }}

      - name: Kubernetes - Create namespaces
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.PROD_WORK_DIR }}/school-deployment
            make k-create-namespaces || true
          EOF

      - name: Kubernetes - Create PV and PVC
        continue-on-error: true
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.PROD_WORK_DIR }}/school-deployment
            make k-apply-volume-prod || true
          EOF

      - name: Kubernetes - Delete secrets
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            kubectl delete secret ghcr-secret --namespace ${{ env.NAMESPACE }} || true
            kubectl delete secret admin-env-secret --namespace ${{ env.NAMESPACE }} || true
            kubectl delete secret api-tls-secret --namespace ${{ env.NAMESPACE }} || true
            kubectl delete secret admin-tls-secret --namespace ${{ env.NAMESPACE }} || true
          EOF

      - name: Kubernetes - Create secrets
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd ${{ secrets.PROD_WORK_DIR }}/school-deployment

            kubectl create secret docker-registry ghcr-secret --namespace ${{ env.NAMESPACE }} \
            --docker-server=https://ghcr.io --docker-username=${{secrets.GHCR_USERNAME}} \
            --docker-password=${{secrets.GHCR_PASSWORD}} --docker-email=${{secrets.GHCR_EMAIL}}
            kubectl create secret generic admin-env-secret --namespace ${{ env.NAMESPACE }} --from-literal=APP_ENV="production"
          EOF

          echo "$API_TLS_CERT" > api.crt
          echo "$API_TLS_KEY" > api.key
          echo "$ADMIN_TLS_CERT" > admin.crt
          echo "$ADMIN_TLS_KEY" > admin.key

          scp -P 22 -i ~/.ssh/id_rsa api.crt api.key admin.crt admin.key ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.PROD_WORK_DIR }}/school-deployment
          rm api.crt api.key admin.crt admin.key

          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd ${{ secrets.PROD_WORK_DIR }}/school-deployment
            set -e
            kubectl create secret generic api-tls-secret \
              --namespace=${{ env.NAMESPACE }} \
              --type=kubernetes.io/tls \
              --from-file=tls.crt=api.crt \
              --from-file=tls.key=api.key || echo "api-tls-secret already exists or failed!"

            rm -f api.crt api.key

            kubectl create secret generic admin-tls-secret \
              --namespace=${{ env.NAMESPACE }} \
              --type=kubernetes.io/tls \
              --from-file=tls.crt=admin.crt \
              --from-file=tls.key=admin.key || echo "admin-tls-secret already exists or failed!"

            rm -f admin.crt admin.key
          EOF

      - name: Kubernetes - Delete config map
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            kubectl delete configmap postgres-env-config --namespace ${{ env.NAMESPACE }} || echo "postgres-env-config already exists or failed!"
            kubectl delete configmap redis-env-config --namespace ${{ env.NAMESPACE }} || echo "redis-env-config already exists or failed!"
            kubectl delete configmap api-env-config --namespace ${{ env.NAMESPACE }} || echo "api-env-config  already exists or failed!"
            kubectl delete configmap api-jwt-config --namespace ${{ env.NAMESPACE }} || echo "api-jwt-config already exists or failed!"
          EOF

      - name: Kubernetes - Create config map
        run: |
          echo "$POSTGRES_ENV" > postgres.env
          echo "$REDIS_ENV" > redis.env
          echo "$API_ENV" > app.env
          echo "$API_JWT_PRIVATE_KEY" > private.pem
          echo "$API_JWT_PUBLIC_KEY" > public.pem

          scp -P 22 -i ~/.ssh/id_rsa postgres.env redis.env app.env private.pem public.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.PROD_WORK_DIR }}/school-deployment
          rm postgres.env redis.env app.env private.pem public.pem

          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.PROD_WORK_DIR }}/school-deployment
            set -e
            kubectl create configmap postgres-env-config --from-env-file=postgres.env --namespace ${{ env.NAMESPACE }} || echo "postgres-env-config already exists or failed!"
            kubectl create configmap redis-env-config --from-env-file=redis.env --namespace ${{ env.NAMESPACE }} || echo "redis-env-config already exists or failed!"
            kubectl create configmap api-env-config --from-file=app.env --namespace ${{ env.NAMESPACE }} || echo "api-env-config already exists or failed!"
            kubectl create configmap api-jwt-config \
              --from-file=private.pem \
              --from-file=public.pem \
              --namespace ${{ env.NAMESPACE }} || echo "api-jwt-config already exists or failed!"
          EOF

      - name: Kubernetes - Apply deployments
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd ${{ secrets.PROD_WORK_DIR }}/school-deployment
            set -e
            make k-apply-deploy-redis-prod
            make k-apply-deploy-postgres-prod
            make k-apply-deploy-api-prod
            make k-apply-deploy-admin-prod
          EOF

      - name: Kubernetes - Apply services
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd ${{ secrets.PROD_WORK_DIR }}/school-deployment
            set -e
            kubectl apply -f ./kubernetes/services/redis.yml --namespace ${{ env.NAMESPACE }}
            kubectl apply -f ./kubernetes/services/postgres.yml --namespace ${{ env.NAMESPACE }}
            kubectl apply -f ./kubernetes/services/api.yml --namespace ${{ env.NAMESPACE }}
            kubectl apply -f ./kubernetes/services/admin.yml --namespace ${{ env.NAMESPACE }}
          EOF

      - name: Kubernetes - Apply ingress
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd ${{ secrets.PROD_WORK_DIR }}/school-deployment
            make k-apply-ingress-prod
          EOF

      - name: Cleanup SSH dir
        run: rm -rf ~/.ssh
